version: "2"
services:
  app:
    container_name: app
    restart: always
    command: nodemon -L --watch ./src/server.js ./src/server.js
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./assets:/usr/app/assets
      - ./src:/usr/app/src
      - ./views:/usr/app/views
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    command: --quiet
    volumes:
      - ./data:/data
    ports:
      - "27017:27017"
